# Base configs
# base URL after / is dependent on the repository name
baseurl: "https://staycool21.github.io/staycool21-photography"
# baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "Luke Welsh Photography"
subtitle: "See the world through my eyes!"
author: "Luke Welsh"
header:
 title: "Luke Welsh"
 subtitle: "Photography"
footer:
 name: "Hey there, I'm Luke ðŸ‘‹"
 bio: "I am a developer, tech aficionado, and racing fanatic. At this point in my life, I am now hoping to learn sports photography."
 github: "If you have time, check out my <a href=\"https://github.com/StayCool21\">GitHub</a> ;)"
# web_design: "LW"
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks

exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
  # twitter: ""
  # instagram: ""
  # dribbble: ""
  linkedin: "https://www.linkedin.com/in/luke-welsh-737886248/"
  github: "https://www.github.com/StayCool21"
